[workspace]
authors = ["Maximilian Linhoff <maximilian.linhoff@cta-observatory.org>"]
channels = ["conda-forge"]
name = "s3-school-2026-git"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
pygments = ">=2.19.2,<3"
